import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/Global/QueryProvider";
import ReduxProvider from "@/redux/ReduxProvider";
import UserLoggedData from "@/components/Global/UserLoggedData";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}  antialiased`}>
        <QueryProvider>
          <ReduxProvider>
            <UserLoggedData>{children}</UserLoggedData>
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
